stages:
  - build
  - test
  - validation
  - package
#  - javafx

build-job:
  stage: build
  script:
    - cd backend
    - mvn clean compile

test-job:
  stage: test
  script:
    - cd backend
    - mvn test

checkstyle-job:
  stage: validation
  script:
    - cd backend
    - mvn checkstyle:check

package-job:
  stage: package
  script:
    - cd backend
    - mvn package
  artifacts:
    when: on_success
    expire_in: 30 days
    paths:
      - "Restaurant/target/*.jar"

